# Generated by Django 4.1.7 on 2024-01-30 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='owner',
            new_name='shop',
        ),
    ]
