# Generated by Django 4.1.7 on 2024-02-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0005_products_manufacture'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='bargainrange',
            field=models.CharField(default=900, max_length=30),
            preserve_default=False,
        ),
    ]
