# Generated by Django 4.1.7 on 2024-02-01 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopkeeper', '0006_products_bargainrange'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('owner', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopkeeper.products')),
            ],
        ),
    ]
