# Generated by Django 4.1.7 on 2024-02-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fastshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='shopaddress',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='shopname',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
