# Generated by Django 4.1.7 on 2024-02-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fastshop', '0002_orders_shopaddress_orders_shopname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='user',
        ),
        migrations.AddField(
            model_name='orders',
            name='customername',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
