# Generated by Django 4.1.7 on 2024-02-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fastshop', '0004_orders_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='customercontact',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='ownercontact',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
